### PR TITLE
Adding cols parameter

### PR DESCRIPTION
**Pull request by lastlivingsoul**
edited /data/data_loader.py and /exp/exp_informer.py, added args.cols paramter, so during training , testing and predicting users can chose certain cols from the data files as the input features.

### CODE REVIEW

**Comment by cookieminions** [comment]
Thanks for your pull request, we think that adding new parameter `cols` requires modifying arguments in `main_informer.py` and you need to specify different cols for different data, so it is better to keep the current code.

**Comment by lastlivingsoul** [comment]
> Thanks for your pull request, we think that adding new parameter `cols` requires modifying arguments in `main_informer.py` and you need to specify different cols for different data, so it is better to keep the current code.

I still find this feature useful, since in some projects you'll need to select features, and the current code will make it difficult to try different input features without changing data files. I think I will edit the code, so that if you do no supply a cols argument, it will automatically use all the features in the file.

**Comment by cookieminions** [comment]
> > Thanks for your pull request, we think that adding new parameter `cols` requires modifying arguments in `main_informer.py` and you need to specify different cols for different data, so it is better to keep the current code.
> 
> I still find this feature useful, since in some projects you'll need to select features, and the current code will make it difficult to try different input features without changing data files. I think I will edit the code, so that if you do no supply a cols argument, it will automatically use all the features in the file.

From this point of view, it is reasonable to increase the `cols` parameter, we will consider this, and hope you can solve how to add and use it in `main_informer.py` more conveniently.

**Comment by lastlivingsoul** [comment]
> > > Thanks for your pull request, we think that adding new parameter `cols` requires modifying arguments in `main_informer.py` and you need to specify different cols for different data, so it is better to keep the current code.
> > 
> > 
> > I still find this feature useful, since in some projects you'll need to select features, and the current code will make it difficult to try different input features without changing data files. I think I will edit the code, so that if you do no supply a cols argument, it will automatically use all the features in the file.
> 
> From this point of view, it is reasonable to increase the `cols` parameter, we will consider this, and hope you can solve how to add and use it in `main_informer.py` more conveniently.

Thanks for your reply. I'll start working on it, and submit another pull request later.

**Pull request closed without merging**
